# logger options
HDMV_ENABLE_TRACE   = True
HDMV_ENABLE_VERBOSE = True
HDMV_ENABLE_WARNING = True

# head_movement_node main loop timer tick-rate
HDMV_MAIN_LOOP_TICK_RATE = 0.5

HDMV_TIMEOUT_TIME_SEC = 5.0

HDMV_FACE_TRACKER_HALF_WIDTH = 640
HDMV_FACE_TRACKER_HALF_HEIGHT = 400

HDMV_EYE_MOVE_HORIZONTAL_COEFF  = -0.002
HDMV_EYE_MOVE_VERTICAL_COEFF    = 0.003
HDMV_HEAD_MOVE_HORIZONTAL_COEFF = -0.00078
HDMV_HEAD_MOVE_VERTICAL_COEFF   = -0.002
